name: ak1_phone_app
description: AK-1 phone controller and AI app
publish_to: "none"
version: 1.0.0+2

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  speech_to_text: ^7.0.0

flutter:
  uses-material-design: true
